name: Buf CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  breaking-change-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: Install Buf CLI and check breaking changes and lint
        uses: bufbuild/buf-action@v1
        with:
          version: 1.57.2
          # 後方互換性の検証を行う
          breaking_against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=proto"
          input: proto # protoディレクトリを指定
